version: '2.1'

services:
  product:
    build: microservices/product-service
    mem_limit: 250m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  recommendation:
    build: microservices/recommendation-service
    mem_limit: 250m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  review:
    build: microservices/review-service
    mem_limit: 250m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
#      eureka:

  product-composite:
    build: microservices/product-composite-service
    mem_limit: 250m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      rabbitmq:
        condition: service_healthy

  eureka:
    build: spring-cloud/eurekaserver
    mem_limit: 250m
    ports:
      - "8761:8761"

  gateway:
    build: spring-cloud/gateway
    environment: 
      - SPRING_PROFILES_ACTIVE=docker
    mem_limit: 250m
    ports:
      - "8443:8443"

  auth-server:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
#      - SERVE_SSL_KEY_STORE=file:/keystore/edge-test.p12
#      - SERVER_SSL_KEY_STORE_PASSWORD=testtest
#    volumes: 
#      - ./keystore:/keystore  
    build: spring-cloud/oauth2authorizationserver
    mem_limit: 250m

  # $ mongo
  mongodb:
    image: mongo:3.6.9
    mem_limit: 250m
    ports:
      - "27017:27017"
    command: mongod --smallfiles
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 20s
      timeout: 5s
      retries: 10

  # $ mysql -uroot -h127.0.0.1 -p
  mysql:
    image: mysql:5.7
    mem_limit: 250m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 20s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.7.8-management
    mem_limit: 250m
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 20s
      timeout: 5s
      retries: 10