server.port: 7001
server.error.include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  auto-index-creation: true

logging:
  level:
    root: INFO
    se.magnus: DEBUG

---
spring.profiles: docker

spring.data.mongodb.host: mongodb

server.port: 8080
